version: 1
'disable_existing_loggers': False
formatters:
  simple:
    format: '%(asctime)s %(name)s %(levelname)s:%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    maxBytes: 50000000
    formatter: simple
    backupCount: 10
    filename: info.log
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    maxBytes: 50000000
    formatter: simple
    backupCount: 10
    filename: error.info
    encoding: utf8
loggers:
  simpleLogging:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [info_file_handler,error_file_handler]
